@echo off
echo Создание виртуального окружения...
python -m venv venv
echo Активация окружения...
call venv\Scripts\activate
echo Установка зависимостей из requirements.txt...
pip install -r requirements.txt
echo Готово! Виртуальное окружение создано и зависимости установлены.
pause
